### ISSUE TITLE
Hoping that this might be able to help me with my project!

### ISSUE THREAD

**Issue by MostHated** [hanbim520/Unity-ThreadPool#1]
Hey there,
    I have been having a tough time trying to figure out how to get something working with my game and have not really been able to find much info on it, so when I saw this it definitely gave me some hope. Here is a bit of background, perhaps you might be able to let me know if this might be able to help me accomplish what I am after?

   I have a server framework that was set up using [this threading framework](https://github.com/chrisa23/Fibrous/tree/master/Fibrous). It was originally a Windows console application but I am trying to get it to work within Unity instead. I have most everything working in Unity already minus things dealing with threading. I was told I could use a dispatcher [such as this](https://github.com/Feynmen/UnityThreading), or [perhaps this](https://github.com/PimDeWitte/UnityMainThreadDispatcher) to make things work. It currently uses things like Action Execute, Action toExecute, etc from what I can tell being the end point of the fiber calls. There are several files and interface in which are threadpool, poolfiber, and similar.

   I tested something that used this.fiber.Enqueue(method); using the second dispatcher by running UnityMainThreadDispatcher.Instance().Enqueue(Method); instead and was able to get the method to fire off, but I believe that might just be bypassing the whole point of the original this.fiber.Enqueue call and just sending it off to the main thread straight away instead of actually queueing the action along with any and all other actions that would end up being queued elsewhere within the framework.

   I, unfortunately, do not know too terribly much about threading, especially when it comes to doing it within Unity, so I am wondering if perhaps your project might be able to help me accomplish what I am after? I am honestly not 100% which parts of what I am trying to do are the problem and what can be done to fix it, but I was told by an asset dev that since I am using Unity 2018.1 and .net4.6 it better utilizes the "TPL" and that I should be able to accomplish my goal. 

   I know that was quite a bit to throw out there, but I am hoping that perhaps you might at least be able to point me in the right direction if your ThreadPool isn't quite what I would need. I am so close to getting my framework fully working, this threading issue is the last piece of the puzzle and I have been stuck on it. : /

I definitely appreciate your time,
Thanks!

**Comment by hanbim520** [comment]
Hello, I'm using the https://github.com/amibar/SmartThreadPool repository code to get it to unity. You can refer to the documentation. For threads, you can check out Google's data.
